import { getComponentSpec } from './componentSpecs'
import type { CanvasNodeDataV2, PaletteTemplate, SourceConfig } from './nodeSpecTypes'

const DEFAULT_REQUEST_TYPE = 'default'
const DEFAULT_REQUEST_SIZE_BYTES = 1024

function createSourceConfig(seed?: PaletteTemplate['seed']): SourceConfig {
  const pattern = seed?.pattern ?? 'poisson'
  const baseRps = seed?.baseRps ?? seed?.throughput ?? 100

  return {
    requestDistribution: [
      {
        type: seed?.requestType ?? DEFAULT_REQUEST_TYPE,
        weight: 1,
        sizeBytes: seed?.requestSizeBytes ?? DEFAULT_REQUEST_SIZE_BYTES
      }
    ],
    defaultWorkload: {
      pattern,
      baseRps,
      bursty: { burstRps: 500, burstDuration: 2000, normalDuration: 8000 },
      spike: { spikeTime: 30_000, spikeRps: 1000, spikeDuration: 5000 },
      sawtooth: { peakRps: 300, rampDuration: 10_000 },
      diurnal: {
        peakMultiplier: 1,
        hourlyMultipliers: [
          0.6, 0.5, 0.45, 0.4, 0.4, 0.5, 0.7, 0.9, 1.1, 1.2, 1.15, 1.05, 1, 1.05, 1.1, 1.2, 1.25,
          1.3, 1.2, 1.05, 0.95, 0.85, 0.75, 0.65
        ]
      }
    }
  }
}

function createCanvasData(template: PaletteTemplate): CanvasNodeDataV2 {
  const spec = getComponentSpec(template.componentType)

  return {
    schemaVersion: 2,
    templateId: template.id,
    componentType: template.componentType,
    structuralRole: template.structuralRole,
    profile: template.profile,
    rendererType: template.rendererType,
    label: template.label,
    subLabel: template.subLabel,
    iconKey: template.iconKey,
    routingStrategy: template.routingStrategy,
    sim:
      template.serializable && spec && template.profile !== 'source'
        ? spec.createDefaultSimulationConfig(template.seed)
        : undefined,
    source: template.profile === 'source' ? createSourceConfig(template.seed) : undefined,
    ui: template.seed?.overloadPreview ? { overloadPreview: true } : undefined
  }
}

export const PALETTE_TEMPLATES: Record<string, PaletteTemplate> = {
  'backend-server': {
    id: 'backend-server',
    componentType: 'microservice',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'computeNode',
    iconKey: 'SERVER',
    label: 'API Server',
    subLabel: 'Long-running Process',
    serializable: true,
    seed: { throughput: 1000, load: 45, queueDepth: 12 }
  },
  'lambda-function': {
    id: 'lambda-function',
    componentType: 'serverless-function',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'computeNode',
    iconKey: 'LAMBDA',
    label: 'Serverless Fn',
    subLabel: 'Event Driven',
    serializable: true,
    seed: { throughput: 250, load: 10, queueDepth: 0 }
  },
  'async-worker': {
    id: 'async-worker',
    componentType: 'batch-worker',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'worker',
    rendererType: 'computeNode',
    iconKey: 'WORKER',
    label: 'Job Worker',
    subLabel: 'Background Task',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 1200, load: 88, queueDepth: 145 }
  },
  'cron-job': {
    id: 'cron-job',
    componentType: 'batch-worker',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'worker',
    rendererType: 'computeNode',
    iconKey: 'CRON',
    label: 'Cron Job',
    subLabel: 'Scheduled Task',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 50, load: 5, queueDepth: 0 }
  },
  'auth-service': {
    id: 'auth-service',
    componentType: 'auth-service',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'computeNode',
    iconKey: 'AUTH',
    label: 'Auth Service',
    subLabel: 'Authentication / Tokens',
    serializable: true,
    seed: { throughput: 800, load: 25, queueDepth: 5 }
  },
  'search-service': {
    id: 'search-service',
    componentType: 'search-service',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'computeNode',
    iconKey: 'SEARCH_SERVICE',
    label: 'Search Service',
    subLabel: 'Query Processing',
    serializable: true,
    seed: { throughput: 900, load: 55, queueDepth: 20 }
  },
  'sidecar-proxy': {
    id: 'sidecar-proxy',
    componentType: 'sidecar',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'computeNode',
    iconKey: 'SIDECAR',
    label: 'Sidecar Proxy',
    subLabel: 'Local Data Plane',
    serializable: true,
    seed: { throughput: 2000, load: 18, queueDepth: 2 }
  },
  'primary-db': {
    id: 'primary-db',
    componentType: 'relational-db',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'database',
    label: 'Primary DB',
    subLabel: 'Relational SQL',
    serializable: true,
    seed: { throughput: 2400, load: 60, queueDepth: 25 }
  },
  'redis-cache': {
    id: 'redis-cache',
    componentType: 'in-memory-cache',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'server',
    label: 'Redis Cache',
    subLabel: 'In-memory key/val',
    serializable: true,
    seed: { throughput: 5000, load: 15, queueDepth: 4 }
  },
  'load-balancer': {
    id: 'load-balancer',
    componentType: 'load-balancer',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'network',
    label: 'Load Balancer (Legacy)',
    subLabel: 'Generic / Backward Compatible',
    serializable: true,
    routingStrategy: 'round-robin',
    seed: { throughput: 10000, load: 10, queueDepth: 4 }
  },
  'load-balancer-l4': {
    id: 'load-balancer-l4',
    componentType: 'load-balancer-l4',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'load-balancer-l4',
    label: 'Load Balancer L4',
    subLabel: 'TCP / UDP',
    serializable: true,
    routingStrategy: 'round-robin',
    seed: { throughput: 25000, load: 8, queueDepth: 6 }
  },
  'load-balancer-l7': {
    id: 'load-balancer-l7',
    componentType: 'load-balancer-l7',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'load-balancer-l7',
    label: 'Load Balancer L7',
    subLabel: 'HTTP / gRPC',
    serializable: true,
    routingStrategy: 'round-robin',
    seed: { throughput: 18000, load: 12, queueDepth: 8 }
  },
  'ingress-controller': {
    id: 'ingress-controller',
    componentType: 'ingress-controller',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'ingress',
    label: 'Ingress Controller',
    subLabel: 'Kubernetes Traffic Routing',
    serializable: true,
    routingStrategy: 'round-robin',
    seed: { throughput: 15000, load: 15, queueDepth: 10 }
  },
  'reverse-proxy': {
    id: 'reverse-proxy',
    componentType: 'reverse-proxy',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'proxy',
    label: 'Reverse Proxy',
    subLabel: 'L7 Routing',
    serializable: true,
    routingStrategy: 'round-robin',
    seed: { throughput: 10000, load: 10, queueDepth: 6 }
  },
  'service-mesh': {
    id: 'service-mesh',
    componentType: 'service-mesh',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'service-mesh',
    label: 'Service Mesh',
    subLabel: 'Service-to-Service Traffic',
    serializable: true,
    routingStrategy: 'round-robin',
    seed: { throughput: 12000, load: 14, queueDepth: 8 }
  },
  'nat-gateway': {
    id: 'nat-gateway',
    componentType: 'nat-gateway',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'nat',
    label: 'NAT Gateway',
    subLabel: 'Outbound Internet',
    serializable: true,
    seed: { throughput: 1000, load: 5, queueDepth: 2 }
  },
  'vpn-gateway': {
    id: 'vpn-gateway',
    componentType: 'vpn-gateway',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'vpn',
    label: 'VPN Gateway',
    subLabel: 'Secure Site-to-Site',
    serializable: true,
    seed: { throughput: 500, load: 10, queueDepth: 1 }
  },
  'routing-rule': {
    id: 'routing-rule',
    componentType: 'routing-rule',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'routing-rule',
    label: 'Routing Rule',
    subLabel: 'Path / Header Matching',
    serializable: true,
    seed: { throughput: 20000, load: 5, queueDepth: 1 }
  },
  'routing-policy': {
    id: 'routing-policy',
    componentType: 'routing-policy',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'routing-policy',
    label: 'Routing Policy',
    subLabel: 'Traffic Distribution',
    serializable: true,
    seed: { throughput: 20000, load: 5, queueDepth: 1 }
  },
  'edge-router': {
    id: 'edge-router',
    componentType: 'edge-router',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'edge-router',
    label: 'Edge Router',
    subLabel: 'Global / Edge Routing',
    serializable: true,
    seed: { throughput: 12000, load: 18, queueDepth: 5 }
  },
  'network-interface': {
    id: 'network-interface',
    componentType: 'high-perf-nic',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'network-interface',
    label: 'Network Interface',
    subLabel: 'NIC / ENI',
    serializable: true,
    seed: { throughput: 40000, load: 6, queueDepth: 2 }
  },
  waf: {
    id: 'waf',
    componentType: 'waf',
    category: 'security-and-identity',
    structuralRole: 'router',
    profile: 'security-filter',
    rendererType: 'securityNode',
    iconKey: 'waf',
    label: 'WAF',
    subLabel: 'Web App Firewall',
    serializable: true,
    seed: { blockRate: 1.2, load: 10, queueDepth: 2 }
  },
  'firewall-rule': {
    id: 'firewall-rule',
    componentType: 'firewall',
    category: 'security-and-identity',
    structuralRole: 'processor',
    profile: 'security-filter',
    rendererType: 'securityNode',
    iconKey: 'firewall',
    label: 'Firewall Rule',
    subLabel: 'L4/L7 Filtering',
    serializable: true,
    seed: { droppedPackets: 0.2, load: 8, queueDepth: 1 }
  },
  'security-group': {
    id: 'security-group',
    componentType: 'firewall',
    category: 'security-and-identity',
    structuralRole: 'processor',
    profile: 'security-filter',
    rendererType: 'securityNode',
    iconKey: 'security-group',
    label: 'Security Group',
    subLabel: 'Network Boundary',
    serializable: true,
    seed: { blockRate: 0.1, droppedPackets: 0.1, load: 5, queueDepth: 1 }
  },
  'vpc-region': {
    id: 'vpc-region',
    structuralRole: 'composite',
    profile: 'composite',
    rendererType: 'vpcNode',
    iconKey: 'cloud',
    label: 'VPC Region',
    subLabel: 'Isolated Network',
    serializable: false
  },
  'availability-zone': {
    id: 'availability-zone',
    structuralRole: 'composite',
    profile: 'composite',
    rendererType: 'vpcNode',
    iconKey: 'az',
    label: 'Availability Zone',
    subLabel: 'Fault Domain',
    serializable: false
  },
  subnet: {
    id: 'subnet',
    structuralRole: 'composite',
    profile: 'composite',
    rendererType: 'vpcNode',
    iconKey: 'subnet',
    label: 'Subnet',
    subLabel: 'Network Partition',
    serializable: false
  },
  'dns-server': {
    id: 'dns-server',
    componentType: 'internal-dns',
    category: 'dns-and-certs',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'server-cog',
    label: 'DNS Server',
    subLabel: 'Internal DNS / Authoritative',
    serializable: true,
    seed: { throughput: 5000, load: 10, queueDepth: 2 }
  },
  'discovery-service': {
    id: 'discovery-service',
    componentType: 'service-registry',
    category: 'orchestration-and-infra',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'book-open',
    label: 'Discovery Service',
    subLabel: 'Service Registry',
    serializable: true,
    seed: { throughput: 3000, load: 15, queueDepth: 2 }
  },
  'client-user': {
    id: 'client-user',
    componentType: 'api-endpoint',
    category: 'compute',
    structuralRole: 'source',
    profile: 'source',
    rendererType: 'serviceNode',
    iconKey: 'monitor',
    label: 'Client App',
    subLabel: 'Browser / Mobile',
    serializable: true,
    seed: { baseRps: 100, requestType: 'GET', requestSizeBytes: 1024 }
  },
  dns: {
    id: 'dns',
    componentType: 'internal-dns',
    category: 'dns-and-certs',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'dns',
    label: 'DNS Resolver',
    subLabel: 'Client-side Name Resolution',
    serializable: true,
    seed: { throughput: 2000, load: 4, queueDepth: 1 }
  },
  cdn: {
    id: 'cdn',
    componentType: 'cdn',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'cdn',
    label: 'CDN',
    subLabel: 'Edge Caching',
    serializable: true,
    seed: { throughput: 50000, load: 5, queueDepth: 4 }
  },
  'api-gateway': {
    id: 'api-gateway',
    componentType: 'api-gateway',
    category: 'network-and-edge',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'globe',
    label: 'API Gateway',
    subLabel: 'Request Router',
    serializable: true,
    seed: { throughput: 8000, load: 20, queueDepth: 10 }
  },
  'message-queue': {
    id: 'message-queue',
    componentType: 'queue',
    category: 'messaging-and-streaming',
    structuralRole: 'storage',
    profile: 'broker',
    rendererType: 'serviceNode',
    iconKey: 'queue',
    label: 'Message Queue',
    subLabel: 'SQS / RabbitMQ',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 3000, load: 10, queueDepth: 0 }
  },
  'message-broker': {
    id: 'message-broker',
    componentType: 'message-broker',
    category: 'messaging-and-streaming',
    structuralRole: 'router',
    profile: 'broker',
    rendererType: 'serviceNode',
    iconKey: 'broker',
    label: 'Event Broker',
    subLabel: 'Kafka / Event Stream',
    serializable: true,
    asyncBoundary: true,
    routingStrategy: 'broadcast',
    seed: { throughput: 100000, load: 10, queueDepth: 0 }
  },
  'pub-sub': {
    id: 'pub-sub',
    componentType: 'pub-sub',
    category: 'messaging-and-streaming',
    structuralRole: 'router',
    profile: 'broker',
    rendererType: 'serviceNode',
    iconKey: 'pub-sub',
    label: 'Pub/Sub',
    subLabel: 'Topic Fan-out',
    serializable: true,
    asyncBoundary: true,
    routingStrategy: 'broadcast',
    seed: { throughput: 15000, load: 12, queueDepth: 0 }
  },
  stream: {
    id: 'stream',
    componentType: 'stream',
    category: 'messaging-and-streaming',
    structuralRole: 'storage',
    profile: 'broker',
    rendererType: 'serviceNode',
    iconKey: 'stream',
    label: 'Event Stream',
    subLabel: 'Ordered Event Log',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 80000, load: 18, queueDepth: 0 }
  },
  'nosql-db': {
    id: 'nosql-db',
    componentType: 'nosql-db',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'nosql',
    label: 'NoSQL DB',
    subLabel: 'DynamoDB / MongoDB',
    serializable: true,
    seed: { throughput: 5000, load: 30, queueDepth: 12 }
  },
  'read-replica': {
    id: 'read-replica',
    componentType: 'relational-db',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'replica',
    label: 'Read Replica',
    subLabel: 'SQL Read Replica',
    serializable: true,
    seed: { throughput: 2000, load: 40, queueDepth: 10 }
  },
  'object-storage': {
    id: 'object-storage',
    componentType: 'object-storage',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'storage',
    label: 'Object Storage',
    subLabel: 'S3 / Blob Store',
    serializable: true,
    seed: { throughput: 500, load: 10, queueDepth: 3 }
  },
  'search-index': {
    id: 'search-index',
    componentType: 'search-index',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'search',
    label: 'Search Index',
    subLabel: 'Elasticsearch',
    serializable: true,
    seed: { throughput: 1500, load: 25, queueDepth: 6 }
  },
  'time-series-db': {
    id: 'time-series-db',
    componentType: 'time-series-db',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'time-series-db',
    label: 'Time-series DB',
    subLabel: 'Metrics / Telemetry',
    serializable: true,
    seed: { throughput: 12000, load: 28, queueDepth: 8 }
  },
  'graph-db': {
    id: 'graph-db',
    componentType: 'graph-db',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'graph-db',
    label: 'Graph DB',
    subLabel: 'Connected Data',
    serializable: true,
    seed: { throughput: 3000, load: 30, queueDepth: 8 }
  },
  'vector-db': {
    id: 'vector-db',
    componentType: 'vector-db',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'vector-db',
    label: 'Vector DB',
    subLabel: 'Embeddings / ANN',
    serializable: true,
    seed: { throughput: 4000, load: 32, queueDepth: 8 }
  },
  'data-warehouse': {
    id: 'data-warehouse',
    componentType: 'data-warehouse',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'data-warehouse',
    label: 'Data Warehouse',
    subLabel: 'OLAP Analytics',
    serializable: true,
    seed: { throughput: 2500, load: 35, queueDepth: 10 }
  },
  'data-lake': {
    id: 'data-lake',
    componentType: 'data-lake',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'data-lake',
    label: 'Data Lake',
    subLabel: 'Raw Analytical Storage',
    serializable: true,
    seed: { throughput: 1800, load: 22, queueDepth: 8 }
  },
  'kv-store': {
    id: 'kv-store',
    componentType: 'kv-store',
    category: 'storage-and-data',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'kv-store',
    label: 'KV Store',
    subLabel: 'Low-latency Key/Value',
    serializable: true,
    seed: { throughput: 15000, load: 16, queueDepth: 4 }
  },
  'push-notification-service': {
    id: 'push-notification-service',
    componentType: 'push-notification-service',
    category: 'real-time-and-media',
    structuralRole: 'processor',
    profile: 'worker',
    rendererType: 'serviceNode',
    iconKey: 'notification',
    label: 'Notification Service',
    subLabel: 'Push / Email / SMS',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 3000, load: 15, queueDepth: 6 }
  },
  'streaming-analytics': {
    id: 'streaming-analytics',
    componentType: 'streaming-analytics',
    category: 'data-infra-and-analytics',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'serviceNode',
    iconKey: 'analytics',
    label: 'Streaming Analytics',
    subLabel: 'Streaming Analytics',
    serializable: true,
    seed: { throughput: 2500, load: 24, queueDepth: 10 }
  },
  'llm-gateway': {
    id: 'llm-gateway',
    componentType: 'llm-gateway',
    category: 'external-and-integration',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'serviceNode',
    iconKey: 'llm-gateway',
    label: 'LLM Gateway',
    subLabel: 'Model Proxy / Guardrails',
    serializable: true,
    seed: { throughput: 600, load: 12, queueDepth: 4 }
  },
  'tool-registry': {
    id: 'tool-registry',
    componentType: 'tool-registry',
    category: 'orchestration-and-infra',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'tool-registry',
    label: 'Tool Registry',
    subLabel: 'Capability Catalog',
    serializable: true,
    seed: { throughput: 900, load: 10, queueDepth: 3 }
  },
  'memory-fabric': {
    id: 'memory-fabric',
    componentType: 'memory-fabric',
    category: 'data-infra-and-analytics',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'memory-fabric',
    label: 'Memory Fabric',
    subLabel: 'Shared Agent Memory',
    serializable: true,
    seed: { throughput: 2500, load: 12, queueDepth: 4 }
  },
  'agent-orchestrator': {
    id: 'agent-orchestrator',
    componentType: 'agent-orchestrator',
    category: 'orchestration-and-infra',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'agent-orchestrator',
    label: 'Agent Orchestrator',
    subLabel: 'Multi-agent Control',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 600, load: 10, queueDepth: 4 }
  },
  'safety-observability-mesh': {
    id: 'safety-observability-mesh',
    componentType: 'safety-observability-mesh',
    category: 'observability',
    structuralRole: 'processor',
    profile: 'observability',
    rendererType: 'serviceNode',
    iconKey: 'safety-mesh',
    label: 'Safety & Observability',
    subLabel: 'AI Eval / Audit / Policy',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 1800, load: 12, queueDepth: 4 }
  },
  'generic-service': {
    id: 'generic-service',
    componentType: 'microservice',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'serviceNode',
    iconKey: 'generic-service',
    label: 'Service',
    subLabel: 'Generic Placeholder',
    serializable: true,
    seed: { throughput: 1000, load: 10, queueDepth: 6 }
  },
  'my-service': {
    id: 'my-service',
    componentType: 'microservice',
    category: 'compute',
    structuralRole: 'processor',
    profile: 'compute-service',
    rendererType: 'serviceNode',
    iconKey: 'my-service',
    label: 'My Service',
    subLabel: 'Named Placeholder',
    serializable: true,
    seed: { throughput: 1000, load: 10, queueDepth: 6 }
  },
  'input-source': {
    id: 'input-source',
    componentType: 'api-endpoint',
    category: 'compute',
    structuralRole: 'source',
    profile: 'source',
    rendererType: 'serviceNode',
    iconKey: 'input-source',
    label: 'Input Source',
    subLabel: 'Entry Point / Ingress',
    serializable: true,
    seed: { baseRps: 100, requestType: 'default', requestSizeBytes: 1024 }
  },
  'output-sink': {
    id: 'output-sink',
    componentType: 'third-party-api-connector',
    category: 'external-and-integration',
    structuralRole: 'sink',
    profile: 'integration',
    rendererType: 'serviceNode',
    iconKey: 'output-sink',
    label: 'Output Sink',
    subLabel: 'Destination / Egress',
    serializable: true,
    seed: { throughput: 100, load: 4, queueDepth: 1 }
  },
  'external-service': {
    id: 'external-service',
    componentType: 'third-party-api-connector',
    category: 'external-and-integration',
    structuralRole: 'sink',
    profile: 'integration',
    rendererType: 'serviceNode',
    iconKey: 'external',
    label: 'External Service',
    subLabel: '3rd Party API',
    serializable: true,
    seed: { throughput: 500, load: 5, queueDepth: 2 }
  },
  sharding: {
    id: 'sharding',
    componentType: 'sharding',
    category: 'auxiliary',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'sharding',
    label: 'Sharding',
    subLabel: 'Shard Routing Strategy',
    serializable: true,
    seed: { throughput: 12000, load: 14, queueDepth: 3 }
  },
  hashing: {
    id: 'hashing',
    componentType: 'hashing',
    category: 'auxiliary',
    structuralRole: 'router',
    profile: 'router',
    rendererType: 'serviceNode',
    iconKey: 'hashing',
    label: 'Hashing',
    subLabel: 'Partition Key Hash',
    serializable: true,
    seed: { throughput: 20000, load: 8, queueDepth: 2 }
  },
  'shard-node': {
    id: 'shard-node',
    componentType: 'shard-node',
    category: 'auxiliary',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'shard-node',
    label: 'Shard Node',
    subLabel: 'Partition Replica',
    serializable: true,
    seed: { throughput: 5000, load: 24, queueDepth: 10 }
  },
  'partition-node': {
    id: 'partition-node',
    componentType: 'partition-node',
    category: 'auxiliary',
    structuralRole: 'storage',
    profile: 'datastore',
    rendererType: 'serviceNode',
    iconKey: 'partition-node',
    label: 'Partition Node',
    subLabel: 'Range / Key Slice',
    serializable: true,
    seed: { throughput: 6000, load: 20, queueDepth: 10 }
  },
  'config-store': {
    id: 'config-store',
    componentType: 'config-store',
    category: 'orchestration-and-infra',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'config',
    label: 'Config Store',
    subLabel: 'Configuration',
    serializable: true,
    seed: { throughput: 1000, load: 10, queueDepth: 2 }
  },
  'secrets-manager': {
    id: 'secrets-manager',
    componentType: 'secrets-manager',
    category: 'orchestration-and-infra',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'secrets',
    label: 'Secrets Manager',
    subLabel: 'Secrets & Keys',
    serializable: true,
    seed: { throughput: 500, load: 5, queueDepth: 1 }
  },
  'feature-flag-service': {
    id: 'feature-flag-service',
    componentType: 'feature-flag-service',
    category: 'devops-and-delivery',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'flags',
    label: 'Feature Flag Service',
    subLabel: 'Feature Flags',
    serializable: true,
    seed: { throughput: 2000, load: 15, queueDepth: 3 }
  },
  'metrics-collector-agent': {
    id: 'metrics-collector-agent',
    componentType: 'metrics-store',
    category: 'observability',
    structuralRole: 'processor',
    profile: 'observability',
    rendererType: 'serviceNode',
    iconKey: 'metrics-collector',
    label: 'Metrics Collector',
    subLabel: 'Agent / Telegraf',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 1000, load: 5, queueDepth: 1 }
  },
  'log-collector-agent': {
    id: 'log-collector-agent',
    componentType: 'centralized-logging',
    category: 'observability',
    structuralRole: 'processor',
    profile: 'observability',
    rendererType: 'serviceNode',
    iconKey: 'log-collector',
    label: 'Log Collector',
    subLabel: 'Fluentd / Promtail',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 5000, load: 10, queueDepth: 2 }
  },
  'log-aggregation-service': {
    id: 'log-aggregation-service',
    componentType: 'centralized-logging',
    category: 'observability',
    structuralRole: 'processor',
    profile: 'observability',
    rendererType: 'serviceNode',
    iconKey: 'log-aggregator',
    label: 'Centralized Logging',
    subLabel: 'Elasticsearch / Loki',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 15000, load: 20, queueDepth: 4 }
  },
  'distributed-tracing-collector': {
    id: 'distributed-tracing-collector',
    componentType: 'distributed-tracing',
    category: 'observability',
    structuralRole: 'processor',
    profile: 'observability',
    rendererType: 'serviceNode',
    iconKey: 'tracing',
    label: 'Tracing Collector',
    subLabel: 'OpenTelemetry',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 10000, load: 18, queueDepth: 3 }
  },
  'alerting-engine': {
    id: 'alerting-engine',
    componentType: 'alerting-hook',
    category: 'observability',
    structuralRole: 'sink',
    profile: 'observability',
    rendererType: 'serviceNode',
    iconKey: 'alerting',
    label: 'Alerting Engine',
    subLabel: 'Pager / Webhook',
    serializable: true,
    asyncBoundary: true,
    seed: { throughput: 200, load: 5, queueDepth: 1 }
  },
  'health-check-monitor': {
    id: 'health-check-monitor',
    componentType: 'health-check-manager',
    category: 'observability',
    structuralRole: 'processor',
    profile: 'control-plane',
    rendererType: 'serviceNode',
    iconKey: 'health-check',
    label: 'Health Check Manager',
    subLabel: 'Synthetic Monitoring',
    serializable: true,
    seed: { throughput: 100, load: 5, queueDepth: 1 }
  }
}

export function getPaletteTemplate(templateId: string | undefined): PaletteTemplate | undefined {
  if (!templateId) return undefined
  return PALETTE_TEMPLATES[templateId]
}

export function instantiateTemplate(templateId: string): CanvasNodeDataV2 {
  const template = getPaletteTemplate(templateId)
  if (!template) {
    throw new Error(`Unknown palette template: ${templateId}`)
  }
  return createCanvasData(template)
}
